### PR TITLE
Small bugfix and Graviton support

### PR DESCRIPTION
**Pull request by mikehearn**
Hi Rohit!

I'm the author of https://graviton.app - an experimental app browser for the JVM. I'm trying to provide an alternative to and compete with applets, Java Web Start, etc. It keeps both the JVM and the apps updated automatically and all it requires is the app to be published to a Maven repository. Or it can even run apps straight for github using jitpack.io

I love what you're doing with Everest and would like it to be a showcase app for the initial limited distribution alpha. Graviton can run apps from Maven repositories, and can run Everest as is. But with this PR I activate an opt-in feature of reusing the browser JVM and stage, so you get a seamless transition from browser shell to Everest and back again. It's maybe easier to show with a video demo:

graviton everest

Unfortunately there is one step I can't do for you - you'd need to upload the (non shaded) JAR to a Maven repository like Central or JCenter. If you merge this PR and do that then Graviton will have a nice showcase app. Are you up for it?

### CODE REVIEW

**Comment by RohitAwate** [comment]
Hi Mike!

This is definitely intriguing and I'd be happy to submit Everest to your platform. Unfortunately, I'm really busy at the moment with my university finals coming up this weekend. I'll take a better look at Graviton once I'm done with my first paper on Friday.

Also, thanks for the tiny fixes. I had fixed the logging one on a different branch but the one in Main slipped by.

Rohit.

**Comment by mikehearn** [comment]
No worries! Focus on your exams, there's no hurry at all.

**Comment by RohitAwate** [comment]
Hello again, Mike! I tried out Everest from Graviton and I'd appreciate if you could clear up a few things I'm unclear on.

I could switch between Graviton and Everest, which is also evident in the GIF you included, so how would uploading a JAR to Maven change/affect these:
> reusing the browser JVM and stage
> seamless transition from browser shell to Everest and back again

Would the readymade JAR allow you to simply download and run the application rather than go through the process of cloning, bullding and downloading it?

I'm afraid I may be asking some dumb questions here but it would be better to have some more clarity on how this works.

**Comment by mikehearn** [comment]
Yes if you upload the app jar to Maven Central, JCenter or some other repository, then the user won't have to clone/compile/etc. The binary you uploaded will be used. If you apply this PR, then the JAR will advertise that it's OK to run in Graviton in the manifest and you'll get the experience you saw.

Signing up for Maven Central or JCenter is a bit of a faff the first time around, but once done it's easy to upload things direct from Gradle.

**Comment by RohitAwate** [comment]
Hi Mike! Apologies for the delay, but I'm finally free now.

I'll create a separate branch for the Graviton-specific changes to `pom.xml` and upload the binaries built off of that to Maven Central. I'm trying to migrate Everest to Java 11, so how does that work under Graviton?

**Comment by mikehearn** [comment]
I want to migrate Graviton to Java 11 too. I suggest signing up to graviton-dev:

https://groups.google.com/forum/#!forum/graviton-dev

I'll post updates there along with news about when I'll be pushing the upgrade to Java 11.

I'd also like to make little badges and buttons so people can advertise in their github READMEs that they are using it! Thanks for being an early adopter!

**Comment by mikehearn** [comment]
By the way, what coordinates are you using? I couldn't find them on search.maven.org

**Comment by RohitAwate** [comment]
Sounds cool! 👍 

> By the way, what coordinates are you using? I couldn't find them on search.maven.org

I haven't uploaded yet, will get it done first thing tomorrow. Should be `com.rohitawate.everest` once done; will let you know otherwise.

Closing this now. All the best with Graviton! :)

**Comment by mikehearn** [comment]
Hello! Any news on the upload?

**Comment by RohitAwate** [comment]
Hi! The artifact is available at Maven Central.
Group ID: `com.github.rohitawate`
Artifact ID: `Everest`

**Comment by mikehearn** [comment]
Nice, thanks!

It downloads fine now. Unfortunately the bug fixes I provided here did not seem to be applied to the `graviton` branch, in particular, it still ignores the primary stage that the app is started with, which means that it doesn't close properly (because you aren't reusing the already existing window).

I realise it's a bit of a hassle, but I don't suppose you could apply the fixes in this PR to the graviton branch and release a new version to Maven?

**Comment by mikehearn** [comment]
I've found a hack that will work for now, although the visual impact isn't as nice. If you do another release of the v8 branch, it'd be good to have the Stage fix in so I can take the hack out.

**Comment by RohitAwate** [comment]
Hi Mike!

I made those changes to `Main.java` (I haven't pushed them to the `graviton` branch yet) while deploying. I'll check again. I did run into a mountain of issues while deploying, so maybe a build without the changes went up on Central.

I'll deploy again with the changes and let you know.

**Pull request closed without merging**
